Repository amplication/docs, pull requests merged in 2023-11, with the labels that each got.

#310 Docs: Custom Prisma Attributes
  docs/custom-code/prisma-custom-attributes.md
  sidebars.js
Labels: documentation

#313 Docs: Using Plugins Page Updates
  docs/dictionary/en-custom.txt
  docs/getting-started/plugins.md
  sidebars.js
Labels: documentation

#315 Docs: Add and Delete User Documentation
  docs/getting-started/assets/authentication/delete_user_popup.png
  docs/getting-started/assets/authentication/disable_auth_plugin.png
  docs/getting-started/assets/authentication/new_user_entity.png
  docs/getting-started/assets/authentication/plugin_installation_cannot_proceed.png
  docs/getting-started/authentication.md
  docs/getting-started/plugins.md
  docs/how-to/add-delete-user-entity.md
  docs/how-to/assets/authentication-entity.png
  docs/how-to/authentication-plugin-examples.md
  sidebars.js
Labels: documentation

#350 Update: Common Id Field Conversion Scenarios For Import Prisma Schema
  docs/getting-started/how-prisma-schemas-are-converted-into-entities.md
Labels: documentation

#353 Bug Fix: Remove Entity Relations Duplicate
  sidebars.js
Labels: bug

#354 Bug Fix: Introduction Page Link To Deploy Page
  docs/welcome.md
Labels: bug

#355 Docs: How To Section Sidebar Restructure
  docs/how-to/base-directories.md
  docs/how-to/commit-changes.md
  docs/how-to/create-entity-field.md
  docs/how-to/create-message-broker.md
  docs/how-to/create-service.md
  sidebars.js
Labels: documentation

#357 Docs: New Git Provider Information on First Service page
  docs/getting-started/first-service.md
Labels: documentation

#362 Update generated-api-sorting.md
  docs/api/generated-api-sorting.md
Labels: documentation

#363 Docs: Import Prisma Schema Updates & Fixes
  docs/how-to/assets/amplication-erd-view.png
  docs/how-to/import-prisma-schema.md
Labels: bug, documentation

#364 Docs: Configure Base Directory page updates
  docs/how-to/base-directories.md
Labels: documentation

#367 Docs: Import Prisma Schema Updates, Fixes, and Consolidations
  docs/dictionary/en-custom.txt
  docs/getting-started/how-prisma-schemas-are-converted-into-entities.md
  docs/how-to/import-prisma-schema.md
Labels: documentation

#369 Docs: `before` and `after` plugin event notes
  docs/plugins/before-after.md
Labels: documentation

#389 Update: Introduction
  docs/dictionary/en-custom.txt
  docs/getting-started/add-plugins-for-service.md
  docs/getting-started/assets/amplicationrc-json-plugin-settings.png
  docs/getting-started/assets/first-service/service-created-successfully.png
  docs/getting-started/assets/install-a-plugin.png
  docs/getting-started/assets/new-database-plugin.png
  docs/getting-started/assets/plugin-settings.png
  docs/getting-started/assets/prettier-plugin-settings-filled-in.png
  docs/getting-started/commit-changes-and-build-new-versions.md
  docs/getting-started/configure-roles-and-permissions.md
  docs/getting-started/first-service.md
  docs/getting-started/set-up-entities.md
  docs/welcome.md
  sidebars.js
Labels: documentation

#390 Docs: How To Set Default Value for an Entity Field
  docs/how-to/assets/default-custom-attribute.png
  docs/how-to/default-value-entity-field.md
  sidebars.js
Labels: documentation

#347 Docs: Adding ESLint, Redis, OpenAI, GitHub Actions, Helm Chart, OpenTelemtry, and Redis Message Broker to the Plugin List
  docs/dictionary/en-custom.txt
  docs/getting-started/plugins.md
Labels: documentation

#405 Documentation: Community Tutorials
  docs/dictionary/en-custom.txt
  docs/tutorials/community-tutorials.md
  sidebars.js
Labels: documentation

#412 Docs: Code Generator Version Control
  docs/how-to/assets/code-generator-version-control.png
  docs/how-to/code-generator-version-control.md
  sidebars.js
Labels: documentation

#392 Docs: FAQ Updates
  docs/faqs/faqs.md
Labels: documentation

#393 Docs: Plugins Overhaul
  docs/dictionary/en-custom.txt
  docs/getting-started/community-plugins.md
  docs/getting-started/plugins.md
  docs/plugins/developing-a-plugin.md
  docs/plugins/plugindev-overview.md
  docs/plugins/publish-your-plugin.md
  docs/plugins/testing-a-plugin.md
  sidebars.js
Labels: documentation

#415 Docs: Sidebar Fix and Improvements
  docs/getting-started/community-plugins.md
  docs/getting-started/relations.md
  docs/how-to/add-delete-user-entity.md
  docs/how-to/base-directories.md
  docs/how-to/change-base-branch.md
  docs/how-to/commit-changes.md
  docs/how-to/create-entity-field.md
  docs/how-to/create-entity.md
  docs/how-to/erd-view-for-amplication-entities.md
  docs/how-to/import-prisma-schema.md
  docs/how-to/set-access-permissions.md
  sidebars.js
Labels: documentation

#411 Docs: Add Open Graph Image and Enhance Open Graph Titles, Descriptions.
  docs/api/metaquery-graphql.md
  docs/getting-started/authentication.md
  docs/getting-started/building-new-versions.md
  docs/getting-started/deploy-docker-desktop.md
  docs/getting-started/first-service.md
  docs/getting-started/plugins.md
  docs/how-to/create-entity-field.md
  docs/how-to/create-entity.md
  docs/how-to/deploy-kubernetes.md
  docs/plugins/plugin-events/create-entity-controller-base.md
  docs/plugins/plugin-events/create-entity-controller-spec.md
  docs/plugins/plugin-events/create-entity-controller.md
  docs/plugins/plugin-events/create-entity-resolver.md
  docs/plugins/plugin-events/create-entity-service-base.md
  docs/plugins/plugin-events/create-entity-service.md
  docs/plugins/plugin-events/create-message-broker-client-options-factory.md
  docs/plugins/plugin-events/create-message-broker-nestjs-module.md
  docs/plugins/plugin-events/create-message-broker-service-base.md
  docs/plugins/plugin-events/create-message-broker-service.md
  docs/plugins/plugin-events/create-message-broker-topics-enum.md
  docs/plugins/plugin-events/create-message-broker.md
  docs/plugins/plugin-events/create-package-json.md
  docs/plugins/plugin-events/create-prisma-schema.md
  docs/plugins/plugin-events/create-seed.md
  docs/plugins/plugin-events/create-server-auth.md
  docs/plugins/plugin-events/create-server-docker-compose-db.md
  docs/plugins/plugin-events/create-server-docker-compose.md
  docs/plugins/plugin-events/create-server-dot-env.md
  docs/plugins/plugin-events/create-server.md
  docs/plugins/plugin-events/create-swagger.md
  docs/plugins/publish-your-plugin.md
  docs/welcome.md
  docusaurus.config.js
  static/img/amplication-docs-social-card.png
Labels: enhancement

#420 Docs: Remove Pro Plan References
  docs/about/licensing.md
  docs/faqs/faqs.md
  docs/getting-started/first-service.md
  docs/getting-started/smart-git-sync.md
  docs/getting-started/sync-with-github.md
  docs/how-to/change-base-branch.md
  docs/how-to/code-generator-version-control.md
  docs/how-to/enterprise-sso.md
  docs/how-to/git-branch-per-service.md
Labels: documentation
